receivers:
  jaeger:
    protocols:
      thrift_binary:
      thrift_http:
  statsd:
    endpoint: "0.0.0.0:8125"
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          static_configs:
            - targets: [ 'host.docker.internal:9512' ]

exporters:
  prometheus:
    endpoint: "0.0.0.0:9502"
  jaeger_thrift:
    endpoint: "http://jaeger:14268/api/traces"
  otlp:
    endpoint:
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [ jaeger ]
      exporters: [ jaeger_thrift ]
    metrics:
      receivers: [ statsd, prometheus ]
      exporters: [ prometheus ]
